- name: Setting up AWS Hostnames
  hosts: all
  gather_facts: no
  remote_user: admin
  become: yes
  tasks:
  - name: Setting up AWS Hostname Correctly
    shell: hostnamectl set-hostname $(curl http://169.254.169.254/latest/meta-data/local-hostname)