- name: Installing Common Packages
  hosts: production
  gather_facts: no
  remote_user: admin
  become: yes
  tasks:
  - name: Adding Dependencies Packages
    apt: 
      name: 
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg 
        - lsb-release
      update_cache: yes